djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from djangoProject import settings
from posts import views
from posts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='home'),
    re_path(r'^user/(\w+)/$', Profile.as_view(), name='profile'),
    re_path(r'^user/(\w+)/post/$', PostPost.as_view(), name='post'),
    re_path(r'^search/$', Search.as_view()),
    re_path(r'^search/hashtag$', SearchTag.as_view()),
    re_path(r'^hashtag.json', TagJson.as_view()),
    re_path(r'^login/$', LoginUser.as_view(), name='login'),
    re_path(r'^register/$', RegisterUser.as_view(), name='register'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('about/', about, name='about'),
    path('logout/', logout_user, name='logout'),
    re_path(r'^user/(\w+)/info/', Info.as_view(), name='info'),
    re_path(r'^user/(\w+)/<int:pk>/delete_post', DeletePost.as_view(), name='delete_post')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

posts/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from user_profile.models import User
from django.contrib.contenttypes.models import ContentType


# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='my_posts')
    text = models.CharField(max_length=300)
    likesCount = models.IntegerField(verbose_name='Лайки',default=0,null=0,blank=True)
    likesAuthors = models.TextField(null=0,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    def get_total_likes(self):
        return self.likes.users.count()

    def get_total_dis_likes(self):
        return self.dis_likes.users.count()


class HashTag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    post = models.ManyToManyField(Post)

    def __str__(self):
        return self.name


# class Like(models.Model):
#     ''' like  comment '''

#     post = models.OneToOneField(Post, related_name="likes", on_delete=models.CASCADE)
#     users = models.ManyToManyField(User, related_name='requirement_post_likes')
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return str(self.post.comment)[:30]


class DisLike(models.Model):
    ''' Dislike  comment '''

    post = models.OneToOneField(Post, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_dis_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.comment)[:30]

posts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.models import User
from user_profile.models import User


class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 80, 'placeholder': 'Write your post here'}),
                           max_length=300)


class SearchForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={'size': 30, 'class': 'form-control search-query'}))


class SearchTagForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={
        'size': 30,
        'class': 'form-control search-tag-query typeahead',
        'id': 'typeahead',
        'autofocus': 'autofocus',
        'placeholder': 'start typing...'
    }))


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    firstname = forms.CharField(label='Firstname', widget=forms.TextInput(attrs={'class': 'form-input'}))
    lastname = forms.CharField(label='Lastname', widget=forms.TextInput(attrs={'class': 'form-input'}))
    patronymic = forms.CharField(label='Patronymic', widget=forms.TextInput(attrs={'class': 'form-input'}))
    country = forms.CharField(label='Country', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'firstname', 'lastname', 'patronymic', 'country')


class ProfileForm(forms.Form):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    firstname = forms.CharField(label='Firstname', widget=forms.TextInput(attrs={'class': 'form-input'}))
    lastname = forms.CharField(label='Lastname', widget=forms.TextInput(attrs={'class': 'form-input'}))
    patronymic = forms.CharField(label='Patronymic', widget=forms.TextInput(attrs={'class': 'form-input'}))
    country = forms.CharField(label='Country', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'firstname', 'lastname', 'patronymic', 'country')

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(
                'This email address is already in use. Please supply a different email address.')
        return email

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))

posts/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.checks import messages
from rest_framework.generics import get_object_or_404
from rest_framework.mixins import UpdateModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from rest_framework import viewsets
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, FormView, DeleteView

from posts.forms import PostForm, SearchForm, SearchTagForm, LoginUserForm, RegisterUserForm, ContactForm, ProfileForm
from user_profile.models import User
from .models import Post, HashTag, DisLike
from .utils import DataMixin

menu = [{'title': "About website", 'url_name': 'about'},
        {'title': "FeedBack", 'url_name': 'contact'}
        ]


class DeletePost(DeleteView):
    def post_delete(self,request, pk):
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':  # If method is POST,
            post.delete()
            return redirect('/')  # Finally, redirect to the homepage.

        return render(request, 'template_name.html', {'post': post})


class Info(View):

    def get(self, request, username):
        user = User.objects.get(username=username)
        if request.user.is_authenticated:
            info = User.objects.all()
            context = {
                'user': user,
                'info': info
            }
            return render(request, 'info.html', context)
        else:
            return redirect('login')


class Index(View):

    def get(self, request):
        context = {'menu': menu, 'text': 'Hello world'}
        return render(request, 'base.html', context)


def about(request):
    contact_list = User.objects.all()
    return render(request, 'about.html', )


class ContactFormView(DataMixin, FormView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Feedback")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('home')


class Profile(View):
    def get(self, request, username):
        likeAuthor = request.GET.get('name')
        id = request.GET.get('id')
        print(likeAuthor ,id)
        if likeAuthor and id:
            post = Post.objects.get(id=id)
            if not likeAuthor+',' in post.likesAuthors:
                print(1)
                authors = post.likesAuthors+likeAuthor+','
                likes = int(post.likesCount)+1
            else:
                print(2)
                authors = post.likesAuthors.replace(likeAuthor+',','')
                likes = int(post.likesCount)-1
            Post.objects.filter(id=id).update(likesAuthors=authors,likesCount=likes)

        likePosts = []
        user = User.objects.get(username=username)
        posts = Post.objects.filter(user=user)
        for i in posts:
            if request.user.username+',' in i.likesAuthors:
                likePosts.append(i.id)

        # posts = Post.objects.all()
        form = PostForm()
        context = {
            'posts': posts,
            'user': user,
            'form': form,
            'likePosts':likePosts,
        }
        return render(request, 'profile.html', context)


class PostPost(View):
    def post(self, request, username):
        form = PostForm(self.request.POST)
        if form.is_valid():
            user = User.objects.get(username=username)
            post = Post(text=form.cleaned_data['text'], user=user)
            post.save()
            words = form.cleaned_data['text'].split(" ")
            for word in words:
                if word.startswith('#'):
                    hashtag, created = HashTag.objects.get_or_create(name=word)
                    hashtag.post.add(post)
        return HttpResponseRedirect('/user/' + username)


class Search(View):
    def get(self, request):
        form = SearchForm()
        context = {'search': form}
        return render(request, 'search.html', context)

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            q = form.cleaned_data['q']
            posts = Post.objects.filter(text__icontains=q)
            context = {'q': q, 'posts': posts}
            return_str = render_to_string('part_views/_post_search.html', context)
            return HttpResponse(json.dumps(return_str), content_type='application/json')
        else:
            HttpResponseRedirect('/search/')


class SearchTag(View):

    def get(self, request):
        form = SearchTagForm()
        context = {'searchtag': form}
        return render(request, 'search_tags.html', context)

    def post(self, request):
        q = request.POST['q']
        form = SearchTagForm()
        tags = HashTag.objects.filter(name__icontains=q)
        context = {'tags': tags, 'searchtag': form, }
        return render(request, 'search_tags.html', context)


class TagJson(View):
    def get(self, request):
        q = request.GET.get('q', '')
        taglist = []
        tags = HashTag.objects.filter(name__icontains=q)
        for tag in tags:
            new = {'q': tag.name, 'count': int(len(tag.post.all()))}
            taglist.append(new)
        return HttpResponse(json.dumps(taglist), content_type="application/json")


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'registration/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Authentication")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Registration")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Page not found</h1>')


def logout_user(request):
    logout(request)
    return redirect('login')


class UpdatePostVote(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'

    def get(self, request, *args, **kwargs):

        post_id = self.kwargs.get('post_id', None)
        opinion = self.kwargs.get('opinion', None)  # like or dislike button clicked

        post = get_object_or_404(Post, id=post_id)

        try:
            # If child DisLike model doesnot exit then create
            post.dis_likes
        except Post.dis_likes.RelatedObjectDoesNotExist as identifier:
            DisLike.objects.create(comment=post)

        try:
            # If child Like model doesnot exit then create
            post.likes
        except Post.likes.RelatedObjectDoesNotExist as identifier:
            Like.objects.create(comment=post)

        if opition.lower() == 'like':

            if request.user in post.likes.users.all():
                post.likes.users.remove(request.user)
            else:
                post.likes.users.add(request.user)
                post.dis_likes.users.remove(request.user)

        elif opition.lower() == 'dis_like':

            if request.user in post.dis_likes.users.all():
                post.dis_likes.users.remove(request.user)
            else:
                post.dis_likes.users.add(request.user)
                post.likes.users.remove(request.user)
        else:
            return HttpResponseRedirect(reverse('profile'))
        return HttpResponseRedirect(reverse('profile'))

posts/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

{% endblock %}

posts/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Feedback</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Отправить</button>
</form>

{% endblock %}

posts/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="features">
    <h1>Delete post</h1>
    <form action="" method="post">
     {% csrf_token %}
    <button class="btn btn-success" type="submit">Delete post</button>
    </form>
</div>
{% endblock %}

posts/templates/profile.html
{% extends 'base.html' %}

{% block navbar %}
    <p class="navbar-text navbar-left">
        <i class="glyphicon glyphicon-user"></i> profile.username {{ profile.username }}
    </p>

    <p class="navbar-text navbar-right">
        <a href="/user/{{ user.username }}"><i class="glyphicon glyphicon-user"></i>{{ user.username }}</a>
    </p>
{% endblock %}

{% block content %}
<div class="row clearfix">

    <div class="col-md-12 column">
        {% if request.user.id == user.id %}
        <form action="post/" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2 fieldWrapper form-group">
                {{ form.text.errors }}
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary"><i class=""></i>Post</button>
        </form>
        {% endif %}
        <button onclick="window.location.href='http://127.0.0.1:8000/search/hashtag';" class="btn btn-primary">Searching</button>

    </div>

    <div class="col-md-12 column">

        {% for post in posts %}

            <div class="card-body">
                {{ post.text }}
                <p></p>
                <p>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                 <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                </svg>
                  <i class="bi bi-person" style="font-size: 2rem;"></i><a>{{ user }}</a>
                  |<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
  <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
</svg>
                    {{ post.created_date | date:"d/m/Y"}}
                  | <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-square-text" viewBox="0 0 16 16">
  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
</svg>
                    <a href="#"><span class="glyphicon glyphicon-comment"></span> Comments</a>
                  |<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-file-plus" viewBox="0 0 16 16">
  <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
</svg>
                    <a href="#"><span class="glyphicon glyphicon-share-alt"></span> Shares</a>
                | <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gem" viewBox="0 0 16 16">
  <path d="M3.1.7a.5.5 0 0 1 .4-.2h9a.5.5 0 0 1 .4.2l2.976 3.974c.149.185.156.45.01.644L8.4 15.3a.5.5 0 0 1-.8 0L.1 5.3a.5.5 0 0 1 0-.6l3-4zm11.386 3.785-1.806-2.41-.776 2.413 2.582-.003zm-3.633.004.961-2.989H4.186l.963 2.995 5.704-.006zM5.47 5.495 8 13.366l2.532-7.876-5.062.005zm-1.371-.999-.78-2.422-1.818 2.425 2.598-.003zM1.499 5.5l5.113 6.817-2.192-6.82L1.5 5.5zm7.889 6.817 5.123-6.83-2.928.002-2.195 6.828z"/>
</svg>
                    <span id="{{post.id}}" class="like" ><span class="{{post.id}}" id="likesCount">{{post.likesCount}}</span> Likes</span>
                    {% if post.hashtag_set.all|length > 0 %}
                  | <i class="icon-tags"></i> Tags:
                    {% for hashtag in post.hashtag_set.all %}
                    <a href="#"><span class="label label-info">{{ hashtag }}</span></a>
                    {% endfor %}
                    {% endif %}
                {% if request.user.id == user.id %}
                    <form action="{% url 'delete_post' post.id %}" method="post">
                    <div>
                     {% csrf_token %}
                        <input type="submit" value="Delete post">
                    </div>
                    </form>
                {% endif %}
                </p>
            </div>

        {% endfor %}

    </div>

    <script>
        likeList = {{likePosts}}
        for (let i = 0; i < likeList.length; i++) {
            console.log(likeList[i])
            document.getElementById(likeList[i]).classList.toggle("liked")
            document.getElementsByClassName(likeList[i])[0].classList.toggle("liked")
        }
        $('.like').on('click', function () {
            likes = document.getElementsByClassName(this.id)[0]
            if(likes.classList.value.split(' ')[1] == "liked"){
                likes.innerHTML = parseInt(likes.innerHTML) - 1
                likes.classList.remove("liked")
                document.getElementById(likes.classList.value.split(' ')[0]).classList.toggle("liked")
            }
            else{
                likes.innerHTML = parseInt(likes.innerHTML) + 1
                likes.classList.add("liked")
                document.getElementById(likes.classList.value.split(' ')[0]).classList.toggle("liked")
            }
            $.ajax({
                type: 'GET',
                data: {
                    name:'{{request.user.username}}',
                    id:this.id,
                }
            })
        })
    </script>

</div>

{% endblock %}

posts/templates/search_tags.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/tag_suggestion.css' %}">
{% endblock %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-6 col-md-offset-3 column" style="">
            <form action="" method="post" id="search-form" autocomplete="off">
                {% csrf_token %}
                <div class="input-group input-group-sm">
                    <div class="tag-suggestion">
                    {{ searchtag.q.errors }}
                    {{ searchtag.q }}
                    </div>

                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">search</button>
                    </span>
                </div>
            </form>
        </div>

    </div>


    <div class="row clearfix">
        <div class="col-md-12 column posts">
            {% for tag in tags %}
                {% for post in tag.post.all %}
                    <div class="well">
                        {{ post.text }}
                        <p></p>
                        <p>
                           <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                 <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                </svg>
                            <i class="bi bi-person" style="font-size: 2rem;"></i><a href="/user/{{ post.user }}/info">{{ post.user }}</a>
                          | <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
  <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
</svg>{{ post.created_date | date:"d/m/Y"}}
                          |  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-square-text" viewBox="0 0 16 16">
  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
</svg><a href="#"><i class="glyphicon glyphicon-comment"></i> Comments</a>|
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-file-plus" viewBox="0 0 16 16">
  <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
</svg>
                    <a href="#"><span class="glyphicon glyphicon-share-alt"></span> Shares</a>
                          | <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gem" viewBox="0 0 16 16">
  <path d="M3.1.7a.5.5 0 0 1 .4-.2h9a.5.5 0 0 1 .4.2l2.976 3.974c.149.185.156.45.01.644L8.4 15.3a.5.5 0 0 1-.8 0L.1 5.3a.5.5 0 0 1 0-.6l3-4zm11.386 3.785-1.806-2.41-.776 2.413 2.582-.003zm-3.633.004.961-2.989H4.186l.963 2.995 5.704-.006zM5.47 5.495 8 13.366l2.532-7.876-5.062.005zm-1.371-.999-.78-2.422-1.818 2.425 2.598-.003zM1.499 5.5l5.113 6.817-2.192-6.82L1.5 5.5zm7.889 6.817 5.123-6.83-2.928.002-2.195 6.828z"/>
</svg><a href="#"><i class="glyphicon glyphicon-share-alt"></i> Likes</a>
                            {% if post.hashtag_set.all|length > 0 %}
                          | <i class="icon-tags"></i> Tags:
                            {% for hashtag in post.hashtag_set.all %}
                            <a href="#"><span class="label label-info">{{ hashtag }}</span></a>
                            {% endfor %}
                            {% endif %}
                        </p>
                    </div>
                {% endfor %}
            {% endfor %}

        </div>
    </div>


{% endblock %}

{% block js %}
    <script src="{% static 'js/typahead.js' %}"></script>
    <script src="{% static 'js/search_tag.js' %}"></script>

{% endblock %}